name: Build and Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      python-versions:
        description: 'JSON array of Python versions (e.g., ["3.11", "3.12"])'
        required: false
      build-sdist:
        description: 'Build sdist?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  sdist:
    name: Build sdist
    if: github.event_name == 'push' || github.event.inputs.build-sdist == 'true'
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ fromJson(github.event.inputs.python-versions || vars.PYTHON_VERSIONS)[-1] }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build sdist
        run: python -m build --sdist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  wheels:
    name: Build Apple Silicon Wheels
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        python-version: ${{ fromJson(github.event.inputs.python-versions || vars.PYTHON_VERSIONS) }}
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel
        run: python -m build --wheel --outdir wheelhouse
        env:
          ARCHFLAGS: "-arch arm64"
          MACOSX_DEPLOYMENT_TARGET: "15.0"

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-py${{ matrix.python-version }}
          path: wheelhouse/*.whl

  publish:
    name: Publish to PyPI
    if: always()
    needs: [wheels]
    runs-on: macos-15
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/macals
    steps:
      - name: Download sdist artifact (if available)
        if: github.event_name == 'push' || github.event.inputs.build-sdist == 'true'
        uses: actions/download-artifact@v4
        with:
          name: sdist

      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          name: wheels-*
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: .
